modLoader="javafml"
loaderVersion="[36,)"
license="LGPL-v3"

[[mods]]
modId="silentriverinthenether"
version="${file.jarVersion}"
displayName="SilentRiverInTheNether"
authors="Team Potato"
description='''

'''